  - type: dnf
    repos:
      copr:
        - swayfx/swayfx        
        - tofik/nwg-shell
        - lihaohong/yazi
        - lionheartp/Hyprland 
        - che/zed
      files:
        add:
          - https://librewolf.net
    install:
      packages:
        # Core Dev & Container Stack
        - git
        - podman-compose
        - podman
        - openssh-clients

        # Utilitários de Terminal & CLI
        - micro
        - btop
        - fzf
        - yazi
        - chafa
        - ImageMagick   
        - ffmpegthumbnailer
        - poppler-utils
        - 7zip
        - tar
        - xz
        - unzip

        # Window Manager & Display Server
        - swayfx
        - gtklock
        - xorg-x11-server-Xwayland

        # Ecossistema Visual & GUI Apps
        #- nwg-look
        - nwg-bar
        - zed
        - godot
        - librewolf

        # Fontes Essenciais
        - google-noto-sans-fonts
        - google-noto-fonts-common
        - fontawesome-fonts

        # Core LXQt (Arranque e Serviços)
        - lxqt-policykit
        #- lxqt-session

        # Network & Hardware Management
        - NetworkManager-wifi
        - iw
        - bluez

        # Gráficos e Aceleração Core
        - mesa-dri-drivers
        - mesa-vulkan-drivers
        - mesa-va-drivers

        # Infraestrutura de Áudio (PipeWire)
        - pipewire
        - pipewire-utils
        - pipewire-alsa
        - pipewire-pulseaudio
        - wireplumber

        # Dependências de Runtime do Noctalia Shell
        - sdbus-cpp
        - libqalculate
        - jemalloc
        - noctalia
        - amixer
        - pamixer
        - brightnessctl  
