# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bluehat
description: bluehat, not red.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - swayfx/swayfx
        - tofik/nwg-shell
        - lihaohong/yazi
        - che/zed
      files:
        - https://repo.librewolf.net/librewolf.repo

    install:
      packages:
        # Core Dev & Container Stack
        - git
        - podman-compose
        - podman
        - openssh-clients

        # Terminal & CLI
        
        - greetd
        - tuigreet
        - grim
        - slurp
        - yazi
        - dunst
        - micro
        - btop
        - fzf
        - chafa
        - bat
        - ImageMagick
        - ffmpegthumbnailer
        - poppler-utils
        - 7zip
        - i3blocks
        - lm_sensors
        - acpi

        # Window Manager & Display Server
        - swayfx
        - gtklock
        - xorg-x11-server-Xwayland

        # Visual & GUI Apps
        - nwg-look
        - nwg-bar
        - steam
        - zed
        - godot
        - librewolf

        # Fonts
        - google-noto-sans-fonts
        - google-noto-fonts-common
        - fontawesome-fonts

        # Core LXQt
        - lxqt-policykit

        # Network & Hardware Management
        - NetworkManager-wifi
        - iw
        - bluez
        - amixer
        - pamixer
        - brightnessctl

  - type: script
    scripts:
      - greetd.sh
