# Configurações globais para todos os blocos
separator=false
separator_block_width=20
markup=pango

[time]
command=sway-ctl get time --format
interval=20

[memory]
command=sway-ctl get memory --perc-usage
interval=10

[cpu]
command=sway-ctl get cpu --usage
interval=10

[temperature]
command=sway-ctl get cpu --temp
interval=5


[battery]
command=sway-ctl get battery --level
interval=1
