# Configurações globais para todos os blocos
separator=false
separator_block_width=20
markup=pango

[time]
command=bash /usr/libexec/sway/scripts/sway-control time --format
interval=20

[memory]
command=bash /usr/libexec/sway/scripts/sway-control memory --perc-usage
interval=10

[cpu]
command=bash /usr/libexec/sway/scripts/sway-control cpu --usage
interval=10

[temperature]
command=bash /usr/libexec/sway/scripts/sway-control cpu --temp
interval=5


[battery]
command=bash /usr/libexec/sway/scripts/sway-control --level
interval=1

