separator=false
separator_block_width=20
markup=pango

[wifi]
command=sway-ctl get wifi --status
interval=10

[sep1]
label=""

[memory]
command=sway-ctl get memory --perc-using
interval=5

[cpu]
command=sway-ctl get cpu --usage
interval=5

[temperature]
command=sway-ctl get cpu --temp
interval=5

[sep2]
label=""

[battery]
command=sway-ctl get battery --level
interval=10

[sep3]
label=""

[date]
command=sway-ctl get time --date-ext-1
interval=3600

[time]
command=sway-ctl get time --time
interval=20
