#!/usr/bin/env bash

gen_ssh() {
	local _provider="$1"

	mkdir -p ~/.ssh/"$_provider"


	ssh-keygen -t ed25519 -f ~/.ssh/"$_provider"/key -C "$USER@git.com"


	cat <<EOF >> ~/.ssh/config
Host $_provider
	HostName $_provider
	User git
	IdentityFile ~/.ssh/$_provider/key
	IdentitiesOnly yes
EOF


	chmod 700 ~/.ssh ~/.ssh/"$_provider"
	chmod 600 ~/.ssh/config ~/.ssh/"$_provider"/key
	chmod 644 ~/.ssh/"$_provider"/key.pub

	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/"$_provider"/key

	cat ~/.ssh/"$_provider"/key.pub
}

gen_sign(){
	local _provider="$1"
	local _name="$2"
	local _sign="$3"

	echo -n "$_sign" > /tmp/ot

	unset SSH_ASKPASS
	ssh-keygen -Y sign -n "$_name" -f ~/.ssh/"$_provider"/key /tmp/ot

	cat /tmp/ot.sig
	rm /tmp/ot /tmp/ot.sig
}

main(){
	local opt="$1"
	shift

	case $opt in
		--ssh) gen_ssh "$@" ;;
		--sign) gen_sign "$@" ;;
	esac
}

main "$@"
