#!/usr/bin/env bash

module-time() {
    local action="$1"
    case "$action" in
        --format)
            date '+󰅐  %I:%M %p - %d/%m'
            ;;
    esac
}

module-memory() {
    local action="$1"
    case "$action" in
        --perc-usage) 
            free | awk '/^Mem:/ {printf "  %.0f%%\n", $3/$2 * 100}'
            ;;
    esac
}

module-cpu() {
    local action="$1"
    case "$action" in
        --temp)
            sensors | awk '/Package id 0/ {print " " $4; exit} /Core 0/ {print " " $3; exit}'
            ;;
        --usage)
            grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5); printf "  %.0f%%\n", usage}'
            ;;
    esac
}

module-battery() {
    local action="$1"
    case "$action" in
       	
        --level)
            local perc val icon status
            perc=$(bash "${BASH_SOURCE[0]}" battery)
            val="${perc%\%}"
            
            local norm=("󰁺" "󰁽" "󰁿" "󰂁" "󰁹")
            local plugged=("󰢜" "󰂇" "󰢝" "󰂊" "󰂅")
            
            if acpi -b | grep -qE 'Charging|Full|Plugged'; then 
                if (( val < 10 ));  then icon="${plugged[0]}"
                elif (( val < 25 )); then icon="${plugged[1]}"
                elif (( val < 60 )); then icon="${plugged[2]}"
                elif (( val < 80 )); then icon="${plugged[3]}"
                else icon="${plugged[4]}"
                fi
            else
                if (( val < 10 ));  then icon="${norm[0]}"
                elif (( val < 25 )); then icon="${norm[1]}"
                elif (( val < 60 )); then icon="${norm[2]}"
                elif (( val < 80 )); then icon="${norm[3]}"
                else icon="${norm[4]}"
                fi
            fi

            printf "%s %s\n" "$icon" "$perc"
            ;;
          *)
            acpi -b | awk -F, '{split($2, cap, "%"); printf "%d%%\n", cap[1]}'
            ;;
    esac
}
main() {
    local mod="$1"
    shift

    case "$mod" in
        time)    module-time $@ ;;
        memory)  module-memory $@ ;;
        cpu)     module-cpu $@ ;;
        battery) module-battery $@ ;;
    esac
}

main "$@"
