#!/usr/bin/env bash

module-time() {
    local action="$1"
    case "$action" in
        --format)
            date '+󰅐  %I:%M %p - %d/%m'
            ;;
    esac
}

module-memory() {
    local action="$1"
    case "$action" in
        --perc-usage) 
            free | awk '/^Mem:/ {printf "  %.0f%%\n", $3/$2 * 100}'
            ;;
    esac
}

module-cpu() {
    local action="$1"
    case "$action" in
        --temp)
            sensors | awk '/Package id 0/ {print " " $4; exit} /Core 0/ {print " " $3; exit}'
            ;;
        --usage)
            grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5); printf "  %.0f%%\n", usage}'
            ;;
    esac
}

module-battery() {
    local action="$1"
    case "$action" in
        --level)
            local perc val icon idx
            local lock_file="/tmp/battery_low.lock"
            
            perc=$(bash "${BASH_SOURCE[0]}" battery)
            val="${perc%\%}"
            
            local norm=("󰁺" "󰁽" "󰁿" "󰂁" "󰁹")
            local plugged=("󰢜" "󰂇" "󰢝" "󰂊" "󰂅")

            local -n icons
            if acpi -b | grep -qE 'Charging|Full|Plugged'; then
                icons=plugged
                rm -f "$lock_file"
            else
                icons=norm
            fi

            if (( val < 10 )); then idx=0
            elif (( val < 25 )); then idx=1
            elif (( val < 60 )); then idx=2
            elif (( val < 80 )); then idx=3
            else                      idx=4
            fi
            
            icon="${icons[$idx]}"

            if [[ "$icons" == "norm" && (( val < 10 )) ]]; then
                if [[ ! -f "$lock_file" ]]; then
                    touch "$lock_file"
                    notify-send -u critical "Battery" "You need to charge your device: $val%"
                fi
            elif [[ "$icons" == "norm" && (( val > 10 )) ]] && [[ -f "$lock_file" ]]; then
                rm -f "$lock_file"
            fi

            printf "%s %s\n" "$icon" "$perc"
            ;;
         *)
            acpi -b | awk -F, '{split($2, cap, "%"); printf "%d%%\n", cap[1]}'
            ;;
    esac
}

main() {
    local mod="$1"
    shift

    case "$mod" in
        time)    module-time $@ ;;
        memory)  module-memory $@ ;;
        cpu)     module-cpu $@ ;;
        battery) module-battery $@ ;;
    esac
}

main "$@"
