#!/usr/bin/env python3
import os
import sys
from pathlib import Path

from desktop_parser import DesktopFile


def get_parsed(path: Path):
    desktops = []
    for file in path.glob("*.desktop"):
        desktops.append(DesktopFile.from_file(str(file)).data.get("Desktop Entry"))
    return desktops


def parse_mult_paths(*paths: Path):
    desktops = []
    for path in paths:
        desktops.extend(get_parsed(path))
    return desktops


def desktop_iter(path: Path, key: str):
    desktops = get_parsed(path)
    for entry in desktops:
        if key in entry:
            yield entry[key]


def get_names(path: Path):
    for key in desktop_iter(path, "Name"):
        if not isinstance(key, dict):
            yield key


def get_exec(path: Path, name: str):
    desktops = get_parsed(path)
    for entry in desktops:
        if "Name" in entry and not isinstance(entry["Name"], dict):
            if name == entry["Name"]:
                return entry["Exec"]
    return None


for name in get_names(Path("/usr/share/applications/")):
    print(name)


print(
    parse_mult_paths(
        Path("/usr/share/applications"), Path.home() / ".local/share/applications/"
    )
)
